.TH "md__r_e_a_d_m_e" 3 "Thu Dec 11 2014" "Version 1.0" "Apache Log Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- COMPILING AND EXECUTING 
You can use the provided Makefile for easy and safe compilation with a single command:
.PP
```bash $ make ```
.PP
To run the compiled executeable file:
.PP
```bash $ \&./sss4910 ```
.PP
After compilation, the Makefile can remove the object files generated for the process:
.PP
```bash $ make objectclean ```
.PP
Or, the executeable and the object files can all be removed:
.PP
```bash $ make clean ``` 
