.TH "Request" 3 "Thu Dec 11 2014" "Version 1.0" "Apache Log Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Request \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBhost\fP"
.br
.ti -1c
.RI "char * \fBclientId\fP"
.br
.ti -1c
.RI "char * \fBuserId\fP"
.br
.ti -1c
.RI "char * \fBstrTime\fP"
.br
.ti -1c
.RI "time_t \fBtime\fP"
.br
.ti -1c
.RI "char * \fBreq\fP"
.br
.ti -1c
.RI "int \fBretCode\fP"
.br
.ti -1c
.RI "int \fBdataSize\fP"
.br
.ti -1c
.RI "char * \fBreferer\fP"
.br
.ti -1c
.RI "char * \fBuserAgent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Apache Log Processor from the source code\&.
