.TH "Statistics" 3 "Thu Dec 11 2014" "Version 1.0" "Apache Log Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Statistics \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtotal200\fP"
.br
.ti -1c
.RI "int \fBtotal404\fP"
.br
.ti -1c
.RI "int \fBtotalInjections\fP"
.br
.ti -1c
.RI "int \fBtotalVisits\fP"
.br
.ti -1c
.RI "long long int \fBhourlyAccess\fP [24]"
.br
.ti -1c
.RI "long long int \fBmonthlyAccess\fP [12]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Apache Log Processor from the source code\&.
