.TH "URL" 3 "Thu Dec 11 2014" "Version 1.0" "Apache Log Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
URL \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBoccurances\fP"
.br
.ti -1c
.RI "char * \fBurl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Apache Log Processor from the source code\&.
